runtime: nodejs12
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/static/\1
    upload: build/(.*\..+)$
    secure: always
  # Catch all handler to index.html
  - url: /.*
    upload: build/index.html
    secure: always
